version: "3.8"

services:
  api:
    build: .
    container_name: optimizer_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # ADD THIS ENVIRONMENT SECTION
    environment:
      - GOOGLE_API_KEY=your key
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: optimizer_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
